version : '3'
services :
  nginx :
    restart : always
    build : Dockerfile.dev
    context : ./nginx
    port : 
      - 80:80
      - 443:443
  node :
    build :
      context : .
      dockerfile : Dockerfile.dev
    ports :
      - "8000:8000"